/* eslint-disable import/prefer-default-export */
export const GET_LISTA_OPERADORES = 'GET_LISTA_OPERADORES';
export const FAIL_LISTA_OPERADORES = 'FAIL_LISTA_OPERADORES';
export const GET_LISTA_OPERADORES_PROVINCIA = 'GET_LISTA_OPERADORES_PROVINCIA';
export const FAIL_LISTA_OPERADORES_PROVINCIA = 'FAIL_LISTA_OPERADORES_PROVINCIA';
