/* eslint-disable import/prefer-default-export */
export const GET_LISTA_ATRACCIONES = 'GET_LISTA_ATRACCIONES';
export const FAIL_LISTA_ATRACCIONES = 'FAIL_LISTA_ATRACCIONES';
export const LOADING_LISTA_ATRACCIONES = 'LOADING_LISTA_ATRACCIONES';
export const GET_LISTA_ACTIVIDADES = 'GET_LISTA_ACTIVIDADES';
export const FAIL_LISTA_ACTIVIDADES = 'FAIL_LISTA_ACTIVIDADES';
export const LOADING_LISTA_ACTIVIDADES = 'LOADING_LISTA_ACTIVIDADES';
